[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-leet = "0.2.0"
rand = "0.6" #Old version used to match version used on leetcode servers
rstest = "0.18.2"
