[toolchain]
# PIN rust version because leetcode uses an old version
# https://support.leetcode.com/hc/en-us/articles/360011833974-What-are-the-environments-for-the-programming-languages-
# channel = "1.74.1"
channel = "stable" # Preferred option for general use (only one channel can be set at a time)
